import Head from "next/head";

import { api, RouterOutputs } from "~/utils/api";
import { SignInButton, UserButton, useUser } from "@clerk/nextjs";
import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";
import Image from "next/image";
import { LoadingPage, LoadingSpinner } from "~/components/Loading.component";

dayjs.extend(relativeTime);

const CreatePostWizard = () => {
  const { user } = useUser();

  if (!user) return null;

  return (
    <div className="flex w-full flex-col gap-3">
      <input
        placeholder="Chirp something"
        className="border-none bg-transparent p-2 outline-0"
      />
    </div>
  );
};

type PostWithUser = RouterOutputs["posts"]["getAll"][number];
const PostView = ({ post, author }: PostWithUser) => {
  return (
    <div key={post.id} className="flex gap-3 border-b border-slate-400 p-4">
      <Image
        src={author.profilePicture}
        alt={`Profile picture of ${author.name}`}
        className="h-8 w-8 rounded-full align-bottom"
        width={56}
        height={56}
      />
      <section className="flex flex-col gap-3 text-slate-300">
        <div className="flex flex-row gap-1.5">
          <p>{`@${author.name}`}</p>

          <p className="font-thin">{`· ${dayjs(post.createdAt).fromNow()}`}</p>
        </div>
        <p>{post.content}</p>
      </section>
    </div>
  );
};

const User = () => {
  const { user } = useUser();
  if (user) return <UserButton />;
  return (
    <div className="flex w-full flex-col gap-3">
      <SignInButton />
    </div>
  );
};

const Feed = () => {
  const { data, isLoading: postsLoading } = api.posts.getAll.useQuery();

  if (postsLoading) return <LoadingPage />;
  if (!data) return <div>Something went wrong...</div>;
  const renderPosts = () => {};
  return (
    <section className="flex flex-col">{data.map((p) => PostView(p))}</section>
  );
};
export default function Home() {
  // Early fetch
  const { data } = api.posts.getAll.useQuery();
  const { user } = useUser();

  return (
    <>
      <Head>
        <title>Chirp</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="h-full w-full border-x border-slate-400 md:max-w-2xl">
          <div className="row-auto flex w-full justify-start gap-3 border-b border-slate-400 p-4">
            <User />
            <CreatePostWizard />
          </div>
          <Feed />
        </div>
      </main>
    </>
  );
}
