import Head from "next/head";

import {api, RouterOutputs} from "~/utils/api";
import {SignInButton, UserButton, useUser} from "@clerk/nextjs";
import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";
import Image from "next/image";

dayjs.extend(relativeTime);

const CreatePostWizard = () => {
  const { user } = useUser();

  if (!user) return null;

  return (
    <div className="flex flex-col gap-3 w-full">
      <input
        placeholder="Chirp something"
        className="bg-transparent border-none outline-0 p-2"
      />
    </div>
  );
}

type PostWithUser = RouterOutputs['posts']['getAll'][number];
const PostView = ({post, author}: PostWithUser) => {


  return (
    <div
      key={post.id}
      className="flex gap-3 p-4 border-b border-slate-400"
    >
      <Image
        src={author.profilePicture}
        alt={`Profile picture of ${author.name}`}
        className="w-8 h-8 rounded-full align-bottom"
        width={56}
        height={56}
      />
      <section
        className="flex flex-col gap-3 text-slate-300"
      >
        <div className="flex flex-row gap-1.5">
          <p>{`@${author.name}`}</p>

          <p className="font-thin">
            {`· ${dayjs(post.createdAt).fromNow()}`}
          </p>
        </div>
        <p>{post.content}</p>
      </section>

    </div>
  );
}

const SignIn = () => {
  const { user } = useUser();
  if (user) return null;
  return (
    <div className="flex flex-col gap-3 w-full">
      <SignInButton />
    </div>
  );
}

export default function Home() {
  const {data, isLoading} = api.posts.getAll.useQuery();

  const renderPosts = () => {
    if (isLoading) return <div>Loading...</div>;
    if (!data) return <div>Something went wrong...</div>;
    return data.map((d) => PostView(d));
  }

  return (
    <>
      <Head>
        <title>Chirp</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center h-screen">
        <div className="w-full h-full md:max-w-2xl border-x border-slate-400">
          <div className="flex row-auto gap-3 justify-start w-full border-b border-slate-400 p-4">
            <SignIn />
            <UserButton />
            <CreatePostWizard />
          </div>
          <section className="flex flex-col">
            {renderPosts()}
          </section>
        </div>
      </main>
    </>
  );
}
