name: CI

on:
  [push, pull_request]

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

jobs:
    build:

        defaults:
          run:
            working-directory: ./chirp/

        runs-on: ubuntu-latest

        steps:
          - name: Checkout
            uses: actions/checkout@v2

          - name: Install dependencies
            run: npm install

          - name: Typecheck
            run: npm run typecheck

          - name: Lint
            run: npm run lint
